### ISSUE TITLE
Essentials link on website dl page goes to jenkins instead of downloading.

### ISSUE THREAD

**Issue by XeroCreator** [TorchAPI/Website#5] opened 2018-12-25 10:48 UTC
Essentials link on website goes to jenkins instead of downloading.

**Comment by Jimmacle** [comment] 2018-12-25 15:01
Can't reproduce, it works fine for me: 
![image](https://user-images.githubusercontent.com/6447556/50424034-dc4d5580-0812-11e9-8ad7-5032ee419073.png)

**Comment by Jimmacle** [comment] 2018-12-25 21:19
Found a few issues (including this one), should all be fixed now.

**Closed by Jimmacle** 2018-12-25 21:19 UTC
